services:
  weather-reels-watcher:
    build: ./Watcher/
    env_file:
      - ./Watcher/.env
    networks:
      - weather-reels

    volumes:
      - type: bind
        source: E:\AssetFolder\BackUp\Video Files\MedalFiles\Clips
        target: /clips
      - type: bind
        source: ./Watcher/config.yaml
        target: /app/config.yaml
        read_only: true
      - type: bind
        source: ./Watcher/credentials.yaml
        target: /app/credentials.yaml
        read_only: true
        
        
  weather-reels-server:
    build: ./Server/
    ports:
      - "8080:8080"
    env_file:
      - ./Server/.env
    networks:
      - weather-reels
    volumes:
      - type: bind
        source: ./Server/config.yaml
        target: /app/config.yaml
        read_only: true


networks:
  weather-reels:
