definitions:
  models.AccessVideoResponse:
    properties:
      url:
        type: string
      video:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.SuccessResponse:
    properties:
      success:
        type: boolean
    type: object
  models.VideoAbortBackupRequest:
    properties:
      filename:
        type: string
      row_id:
        type: string
      video_s3_upload_id:
        type: string
    type: object
  models.VideoCompleteBackupRequest:
    properties:
      completed_parts:
        items:
          $ref: '#/definitions/models.VideoCompletedPart'
        type: array
      filename:
        type: string
      row_id:
        type: string
      video_s3_upload_id:
        type: string
    type: object
  models.VideoCompletedPart:
    properties:
      etag:
        type: string
      part_number:
        type: integer
    type: object
  models.VideoStartBackupRequest:
    properties:
      filelength:
        type: number
      filename:
        type: string
      filesize:
        type: integer
    type: object
  models.VideoStartBackupResponse:
    properties:
      row_id:
        type: string
      thumbnail_s3_url:
        type: string
      video_s3_upload_id:
        type: string
      video_s3_urls:
        items:
          $ref: '#/definitions/models.VideoURLPart'
        type: array
    type: object
  models.VideoURLPart:
    properties:
      offset:
        type: integer
      part_number:
        type: integer
      request_url:
        type: string
      size:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/v1/videos/abort:
    post:
      consumes:
      - application/json
      description: Aborts a multipart video upload and marks the failed record
      parameters:
      - description: Video information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VideoAbortBackupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Abort video upload
      tags:
      - videos
  /api/v1/videos/backup:
    post:
      consumes:
      - application/json
      description: Starts a multipart video upload, creating S3 URLS and marks the
        record as pending
      parameters:
      - description: Video information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VideoStartBackupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.VideoStartBackupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Starts a video upload
      tags:
      - videos
  /api/v1/videos/complete:
    post:
      consumes:
      - application/json
      description: Completes a multipart video upload and marks the record as completed
      parameters:
      - description: Video information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VideoCompleteBackupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Completes a Video Upload
      tags:
      - videos
  /api/v1/videos/fetch/{video}:
    get:
      description: Generate a presigned URL for a video file
      parameters:
      - description: Video filename
        in: path
        name: video
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccessVideoResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get URL for a video
      tags:
      - videos
  /api/v1/videos/verify:
    put:
      consumes:
      - application/json
      description: Verifies videos that are already uploaded, returning a list of
        ones that are not verified
      parameters:
      - description: List of video filenames
        in: body
        name: request
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                type: string
              type: array
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Verify uploaded Videos
      tags:
      - videos
swagger: "2.0"
