# USER IDS MUST BE UNIQUE!

users: # List of all the users of the application
  - userId: 'AbsolutelyBonkersUserId1' # UserID, send this to their client
    displayName: "NumberOneUserForANumberOneClip" # The display name to be used on clips in the front page    
    role: "admin" # Admin role, will get access to delete videos and 
    totalStorageGB: 350 # The amount of storage the user gets in the application, in Gigabytes
    maxStorageReplacementStrategy: "replace" # 'replace': Removes old videos to allow for newer ones to be auto uploaded, 'deny': Denies upload until older videos are deleted

  - userId: 'AbsolutelyBonkersUserId2' # UserID, send this to their client
    displayName: "IAmTheUserNumber2" # The display name to be used on clips in the front page
    role: "user" # Standard user, can upload and view. Only able to delete their own video
    totalStorageGB: 0 # Leave to zero to give infinite storage
    maxStorageReplacementStrategy: "deny" # 'replace': Removes old videos to allow for newer ones to be auto uploaded, 'deny': Denies upload until older videos are deleted

    

